apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beer-horoscope-ui
  name: beer-horoscope-ui
  namespace: beer-rec-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beer-horoscope-ui
  template:
    metadata:
      labels:
        app: beer-horoscope-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/beer-rec-system/beer-horoscope-ui:latest
        name: beer-horoscope-ui
        ports:
          - containerPort: 8081
        env:
          - name: BACKEND
            value: "beer-rec-rest-api.beer-rec-system:5000"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: beer-horoscope-ui
  name: beer-horoscope-ui
  namespace: beer-rec-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - name: ports
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: beer-horoscope-ui
  type: ClusterIP
---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: beer-horoscope
  namespace: beer-rec-system
  labels:
    app: beer-horoscope-ui
  annotations:
    openshift.io/host.generated: 'true'
    argocd.argoproj.io/sync-wave: "2"
spec:
  to:
    kind: Service
    name: beer-horoscope-ui
    weight: 100
  port:
    targetPort: ports
  wildcardPolicy: None

